In [9]:

import numpy as np 
import pandas as pd 

In [20]:
df = pd.read_csv('Student_performance_data _.csv')

In [21]:
df.head()

StudentID  Age  Gender  Ethnicity  ParentalEducation  StudyTimeWeekly  \
0       1001   17       1          0                  2        19.833723   
1       1002   18       0          0                  1        15.408756   
2       1003   15       0          2                  3         4.210570   
3       1004   17       1          0                  3        10.028829   
4       1005   17       1          0                  2         4.672495   

   Absences  Tutoring  ParentalSupport  Extracurricular  Sports  Music  \
0         7         1                2                0       0      1   
1         0         0                1                0       0      0   
2        26         0                2                0       0      0   
3        14         0                3                1       0      0   
4        17         1                3                0       0      0   

   Volunteering       GPA  GradeClass  
0             0  2.929196         2.0  
1             0  3.042915         1.0  
2             0  0.112602         4.0  
3             0  2.054218         3.0  
4             0  1.288061         4.0

In [22]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df.iloc[:,0:-1],df.iloc[:,-1],test_size=0.2,random_state=2)

In [23]:
from sklearn.linear_model import LogisticRegression
from sklearn.tree import DecisionTreeClassifier

In [24]:
clf1 = LogisticRegression()
clf2 = DecisionTreeClassifier()

In [25]:
clf1.fit(X_train,y_train)
clf2.fit(X_train,y_train)

C:\Users\hpcod\AppData\Roaming\Python\Python311\site-packages\sklearn\linear_model\_logistic.py:469: ConvergenceWarning: lbfgs failed to converge (status=1):
STOP: TOTAL NO. of ITERATIONS REACHED LIMIT.

Increase the number of iterations (max_iter) or scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(


DecisionTreeClassifier()

In [26]:
y_pred1 = clf1.predict(X_test)
y_pred2 = clf2.predict(X_test)

In [27]:
from sklearn.metrics import accuracy_score,confusion_matrix
print("Accuracy of Logistic Regression",accuracy_score(y_test,y_pred1))
print("Accuracy of Decision Trees",accuracy_score(y_test,y_pred2))

Accuracy of Logistic Regression 0.6680584551148225
Accuracy of Decision Trees 0.9206680584551148


In [28]:
confusion_matrix(y_test,y_pred1)

array([[  0,   9,   5,   0,   1],
       [  0,  24,  28,   2,   8],
       [  0,  11,  41,  17,   4],
       [  0,   5,  30,  29,  23],
       [  0,   1,   6,   9, 226]], dtype=int64)

In [30]:
print("Logistic Regression Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,5)))

Logistic Regression Confusion Matrix



0   1   2   3    4
0  0   9   5   0    1
1  0  24  28   2    8
2  0  11  41  17    4
3  0   5  30  29   23
4  0   1   6   9  226

In [32]:

print("Decision Tree Confusion Matrix\n")
pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,5)))

Decision Tree Confusion Matrix



0   1   2   3    4
0  13   0   0   0    2
1   3  52   3   2    2
2   2   1  66   3    1
3   1   4   2  75    5
4   1   2   2   2  235

In [33]:
result = pd.DataFrame()
result['Actual Label'] = y_test
result['Logistic Regression Prediction'] = y_pred1
result['Decision Tree Prediction'] = y_pred2

In [34]:
result.sample(10)

Actual Label  Logistic Regression Prediction  Decision Tree Prediction
627            3.0                             3.0                       3.0
240            1.0                             2.0                       1.0
36             4.0                             4.0                       4.0
2272           4.0                             1.0                       1.0
1152           1.0                             1.0                       1.0
903            1.0                             2.0                       1.0
2269           1.0                             4.0                       0.0
556            4.0                             4.0                       4.0
1443           4.0                             4.0                       4.0
671            3.0                             2.0                       3.0

In [35]:
from sklearn.metrics import recall_score,precision_score,f1_score

In [38]:
print("For Logistic regression Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred1),columns=list(range(0,5)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred1))
print("Recall - ",recall_score(y_test,y_pred1))
print("F1 score - ",f1_score(y_test,y_pred1))

For Logistic regression Model
--------------------------------------------------
   0   1   2   3    4
0  0   9   5   0    1
1  0  24  28   2    8
2  0  11  41  17    4
3  0   5  30  29   23
4  0   1   6   9  226
--------------------------------------------------


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [40]:
print("For DT Model")
print("-"*50)
cdf = pd.DataFrame(confusion_matrix(y_test,y_pred2),columns=list(range(0,5)))
print(cdf)
print("-"*50)
print("Precision - ",precision_score(y_test,y_pred2))
print("Recall - ",recall_score(y_test,y_pred2))
print("F1 score - ",f1_score(y_test,y_pred2))

For DT Model
--------------------------------------------------
    0   1   2   3    4
0  13   0   0   0    2
1   3  52   3   2    2
2   2   1  66   3    1
3   1   4   2  75    5
4   1   2   2   2  235
--------------------------------------------------


ValueError: Target is multiclass but average='binary'. Please choose another average setting, one of [None, 'micro', 'macro', 'weighted'].

In [41]:
precision_score(y_test,y_pred1,average=None)

C:\Users\hpcod\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


array([0.        , 0.48      , 0.37272727, 0.50877193, 0.86259542])

In [42]:
precision_score(y_test,y_pred2,average=None)

array([0.65      , 0.88135593, 0.90410959, 0.91463415, 0.95918367])

In [43]:
recall_score(y_test,y_pred2,average=None)

array([0.86666667, 0.83870968, 0.90410959, 0.86206897, 0.97107438])

In [44]:
recall_score(y_test,y_pred1,average=None)

array([0.        , 0.38709677, 0.56164384, 0.33333333, 0.9338843 ])

In [45]:
from sklearn.metrics import precision_score,recall_score,f1_score

In [46]:
precision_score(y_test,y_pred1,average='weighted')

C:\Users\hpcod\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))


0.6471405854005869

In [47]:
recall_score(y_test,y_pred1,average='weighted')

0.6680584551148225

In [48]:
f1_score(y_test,y_pred1,average='weighted')

0.6500109056023017

In [49]:
from sklearn.metrics import classification_report
print(classification_report(y_test,y_pred1))

              precision    recall  f1-score   support

         0.0       0.00      0.00      0.00        15
         1.0       0.48      0.39      0.43        62
         2.0       0.37      0.56      0.45        73
         3.0       0.51      0.33      0.40        87
         4.0       0.86      0.93      0.90       242

    accuracy                           0.67       479
   macro avg       0.44      0.44      0.44       479
weighted avg       0.65      0.67      0.65       479



C:\Users\hpcod\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\hpcod\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
C:\Users\hpcod\AppData\Roaming\Python\Python311\site-packages\sklearn\metrics\_classification.py:1531: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} i